[package]
name = "urdf-viz"
version = "0.29.0"
authors = ["Takashi Ogura <t.ogura@gmail.com>"]
description = "URDF visualization"
license = "Apache-2.0"
keywords = ["robotics", "urdf", "visualization"]
categories = ["visualization"]
repository = "https://github.com/openrr/urdf-viz"
documentation = "http://docs.rs/urdf-viz"
exclude = [".github/*", "img/*"]
edition = "2018"

[workspace]
resolver = "2"
members = ["examples/wasm"]

[features]
default = []
assimp = ["assimp-crate", "assimp-sys"]

# Note: k, kiss3d, serde, urdf-rs, and wasm-bindgen are public dependencies.
[dependencies]
collada = "0.13"
k = "0.25"
kiss3d = "0.31"
nom_stl = "0.2"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
thiserror = "1.0"
tracing = { version = "0.1", features = ["log"] }
urdf-rs = "0.6"

assimp-crate = { package = "assimp", version = "0.3.1", optional = true }
assimp-sys = { version = "0.3.1", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
actix-web = "3"
ctrlc = { version = "3", features = ["termination"] }
tracing-subscriber = "0.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
base64 = "0.13"
futures = "0.3"
getrandom = { version = "0.2", features = ["js"] }
js-sys = "0.3.31"
serde_json = "1"
serde_qs = "0.8"
tokio = { version = "1", features = ["sync"] }
url = "2"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "Window",
    "Location",
    "Url",
    "FileReader",
    "Blob",
    "File",
    "Response",
    "WebGlRenderingContext",
] }
